{
 "title": "Dotnext.Demo.Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "${VAR_APP}" },
   {
    "name": "env",
    "label": "environment",
    "query": {
     "query": "label_values(application_uptime_milliseconds{exported_job=\"${app}\"},env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(application_uptime_milliseconds{exported_job=\"${app}\", env=\"${env}\"},exported_instance)"
    }
   },
   {
    "name": "message",
    "label": "message",
    "query": {
     "query": "label_values(handler_success_count_total{exported_job=\"${app}\", env=\"${env}\", exported_instance=~\"${instance}\"},message)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_uptime_milliseconds{exported_job=\"${app}\", env=\"${env}\", exported_instance=~\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(application_uptime_milliseconds{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sample Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_check{name=\"sample\", exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname=~\"demo_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(handler_fail_count_total{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "handler_success_count_total{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Thoughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(handler_success_count_total{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, increase(handler_latency_milliseconds_bucket{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}[$__rate_interval]))",
     "legendFormat": "{{message}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Duration ${message}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "repeat": "message",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "handler_duration_milliseconds{exported_job=\"${app}\", env=\"${env}\", exported_instance=~\"${instance}\", message=~\"${message}\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Latency 95 percentile ${message}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "repeat": "message",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, increase(handler_latency_milliseconds_bucket{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\", message=~\"${message}\"}[$__rate_interval]))",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time_seconds_total{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Process memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{exported_job=\"${app}\", env=\"${env}\", exported_instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}