groups:
- name: demo_service
  rules:
  - alert: demo_service_unhealthy.production
    expr: health{job="Dotnext.Demo.Service", env="production"} == 0
    for: 5m
    labels:
      priority: low
      severity: warning
    annotations:
      summary: "{{ $labels.app }} is unhealthy on '{{ $labels.instance }}'"
  - alert: demo_service_order_latency.production
    expr: |
      histogram_quantile(0.95, rate(handler_latency_milliseconds_bucket
      {message="OrderMessage", job="Dotnext.Demo.Service", env="production"}[24h]))/1000/60
      > 10
    for: 5m
    labels:
      priority: medium
      severity: critical
    annotations:
      summary: "Latency for {{ $labels.message }} is above 10 minutes"
  - alert: demo_service_user_latency.production
    expr: |
      histogram_quantile(0.95, rate(handler_latency_milliseconds_bucket
      {message="UserMessage", job="Dotnext.Demo.Service", env="production"}[24h]))/1000/60
      > 10
    for: 5m
    labels:
      priority: medium
      severity: critical
    annotations:
      summary: "Latency for {{ $labels.message }} is above 10 minutes"

